[package]
name = "keycloak"
version = "20.0.101"
authors = ["Alexander Korolev <alexander.korolev.germany@gmail.com>"]
edition = "2021"
categories = ["api-bindings", "asynchronous"]
description = """
Keycloak Admin REST API.
"""
homepage = "https://github.com/kilork/keycloak"
keywords = ["api", "async", "keycloak", "rest"]
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/kilork/keycloak"

[dependencies]
reqwest = { version = "0.11", features = [ "json" ] }
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }
serde_with = "2"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1", features = [ "full" ] }
scraper = "0.13"
heck = "0.4"
structopt = "0.3"
toml = "0.5"
